language: node_js
node_js:
  - "6"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build.prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 717793113de058e725dca0a92ed8c519d6b11f7c
  local_dir: dist
  on:
    branch: master
